import {
  FinancialRequest,
  FinancialRequestStatus,
  FinancialRequestType,
} from "./models/financial-request.model";

let db: Array<FinancialRequest> = [
  {
    id: 1,
    type: FinancialRequestType.Purchase,
    name: "Purchase Request 1",
    description: "Request to purchase office supplies",
    amount: 100,
    currency: "USD",
    employee_name: "John Doe",
    status: FinancialRequestStatus.Pending,
    created_at: new Date("2024-07-19T08:30:00Z"),
    approved_amount: 90,
  },
  {
    id: 2,
    type: FinancialRequestType.Reimbursement,
    name: "Reimbursement Request 1",
    description: "Reimbursement for travel expenses",
    amount: 150,
    currency: "EUR",
    employee_name: "Jane Smith",
    status: FinancialRequestStatus.Approved,
    created_at: new Date("2024-07-18T10:15:00Z"),
    updated_at: new Date("2024-07-20T14:20:00Z"),
    approved_amount: 140,
  },
  {
    id: 3,
    type: FinancialRequestType.Purchase,
    name: "Purchase Request 2",
    description: "Request to purchase new laptops",
    amount: 80,
    currency: "USD",
    employee_name: "Alice Johnson",
    status: FinancialRequestStatus.Pending,
    created_at: new Date("2024-07-17T12:45:00Z"),
    approved_amount: 75,
  },
  {
    id: 4,
    type: FinancialRequestType.Reimbursement,
    name: "Reimbursement Request 2",
    description: "Reimbursement for conference fees",
    amount: 120,
    currency: "EUR",
    employee_name: "Bob Brown",
    status: FinancialRequestStatus.Approved,
    created_at: new Date("2024-07-16T09:00:00Z"),
    updated_at: new Date("2024-07-18T11:30:00Z"),
    approved_amount: 110,
  },
  {
    id: 5,
    type: FinancialRequestType.Purchase,
    name: "Purchase Request 3",
    description: "Request to purchase marketing materials",
    amount: 200,
    currency: "USD",
    employee_name: "Eve Green",
    status: FinancialRequestStatus.Pending,
    created_at: new Date("2024-07-15T14:20:00Z"),
    approved_amount: 180,
  },
  {
    id: 6,
    type: FinancialRequestType.Reimbursement,
    name: "Reimbursement Request 3",
    description: "Reimbursement for team building event",
    amount: 90,
    currency: "EUR",
    employee_name: "Chris White",
    status: FinancialRequestStatus.Approved,
    created_at: new Date("2024-07-14T11:10:00Z"),
    updated_at: new Date("2024-07-17T16:45:00Z"),
    approved_amount: 85,
  },
  {
    id: 7,
    type: FinancialRequestType.Purchase,
    name: "Purchase Request 4",
    description: "Request to purchase software licenses",
    amount: 110,
    currency: "USD",
    employee_name: "Grace Black",
    status: FinancialRequestStatus.Pending,
    created_at: new Date("2024-07-13T09:30:00Z"),
    approved_amount: 105,
  },
  {
    id: 8,
    type: FinancialRequestType.Reimbursement,
    name: "Reimbursement Request 4",
    description: "Reimbursement for client entertainment",
    amount: 180,
    currency: "EUR",
    employee_name: "David Gray",
    status: FinancialRequestStatus.Approved,
    created_at: new Date("2024-07-12T13:00:00Z"),
    updated_at: new Date("2024-07-15T17:00:00Z"),
    approved_amount: 170,
  },
  {
    id: 9,
    type: FinancialRequestType.Purchase,
    name: "Purchase Request 5",
    description: "Request to purchase office furniture",
    amount: 95,
    currency: "USD",
    employee_name: "Emma Brown",
    status: FinancialRequestStatus.Pending,
    created_at: new Date("2024-07-11T16:45:00Z"),
    approved_amount: 90,
  },
  {
    id: 10,
    type: FinancialRequestType.Reimbursement,
    name: "Reimbursement Request 5",
    description: "Reimbursement for training course",
    amount: 130,
    currency: "EUR",
    employee_name: "Frank Johnson",
    status: FinancialRequestStatus.Approved,
    created_at: new Date("2024-07-10T08:00:00Z"),
    updated_at: new Date("2024-07-13T10:30:00Z"),
    approved_amount: 120,
  },
];

let nextId = db.length + 1;

const incrementNextId = () => {
  nextId++;
};

export { db, nextId, incrementNextId };
